// <auto-generated />
namespace Rdio.Mvc.Persistence.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Remodelado_banco_de_dados : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Remodelado_banco_de_dados));
        
        string IMigrationMetadata.Id
        {
            get { return "201607191742220_Remodelado_banco_de_dados"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
